export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";


export const SET_USER_DESCRIPTION_SUCCESS = "SET_USER_DESCRIPTION_SUCCESS";
export const SET_USER_DESCRIPTION_FAIL = "SET_USER_DESCRIPTION_FAIL";

export const UPLOAD_PROFILE_PICTURE_SUCCESS = "UPLOAD_PROFILE_PICTURE";
export const UPLOAD_PROFILE_PICTURE_FAIL = "UPLOAD_PROFILE_PICTURE_FAIL";


export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";
export const GET_REPORTED_POSTS_SUCCESS = "GET_REPORTED_POSTS_SUCCESS";
export const GET_REPORTED_POSTS_FAIL = "GET_REPORTED_POSTS_FAIL";
export const POST_MESSAGE_SUCCESS = "POST_MESSAGE_SUCCESS";
export const POST_MESSAGE_FAIL = "POST_MESSAGE_FAIL";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";
export const REPORT_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const REPORT_POST_FAIL = "DELETE_POST_FAIL";

export const COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS";
export const COMMENT_POST_FAIL = "COMMENT_POST_FAIL";


export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";


export const UPLOADE_PICTURE_SUCCESS = "UPLOADE_PICTURE_SUCCESS";
export const UPLOADE_PICTURE_FAIL = "UPLOADE_PICTURE_FAIL";

export const LIKE_COMMENT_SUCCESS = "LIKE_COMMENT_SUCCESS";
export const LIKE_COMMENT_FAIL = "LIKE_COMMENT_FAIL";
